all:
	gcc sieve.c -O3 -o sieve
	gcc sieve1.c -O3 -o sieve1
	gcc sieve2.c -O3 -o sieve2
	gcc sieve3.c -O3 -o sieve3
	gcc sieve4.c -O3 -o sieve4
	gcc sieve5.c -O3 -o sieve5
	gcc sieve6.c -O3 -o sieve6
	gcc sieve7.c -O3 -o sieve7
	gcc sieve8.c -O3 -o sieve8
	gcc sieve9.c -O3 -o sieve9
