all:
	gcc sieve.c -O3 -o sieve
	gcc sieve1.c -O3 -o sieve1
	gcc sieve2.c -O3 -o sieve2
	gcc sieve3.c -O3 -o sieve3
	gcc sieve4.c -O3 -o sieve4
	gcc sieve5.c -O3 -o sieve5
	gcc sieve6.c -O3 -o sieve6
	gcc sieve7.c -O3 -o sieve7
	gcc sieve8.c -O3 -o sieve8
	gcc sieve9.c -O3 -o sieve9

benchmark:
	time -p ./sieve
	time -p ./sieve1
	time -p ./sieve2
	time -p ./sieve3
	time -p ./sieve4
	time -p ./sieve5
	time -p ./sieve6
	time -p ./sieve7
	time -p ./sieve8
	time -p ./sieve9
